changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
        - feat
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Documentation changes
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
