on:
  push:
    tags:
      - 'v*'
#  workflow_dispatch: {}

env:
  GOTELEMETRY: off

permissions:
  contents: write

name: Make Release
jobs:
  release:
    name: Release
    #needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Validate Module
        run: |
          go mod tidy
          git diff --exit-code
          go test ./...

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          #files: |
          #  dist/**
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
